### ISSUE TITLE
"Initialize" misspelled?

### ISSUE THREAD

**Issue by justinas** [spf13/nitro#1]
There's no such word as `Initalize`. Should that method be called `Initialize` or is this a deliberate naming decision?

**Comment by spf13** [comment]
Just a typo that autocomplete helped me not catch. Thanks.

Steve Francia
spf13.com
@spf13

On Jul 11, 2013, at 4:45 PM, justinas notifications@github.com wrote:

There's no such word as Initalize. Should that method be called
Initializeor is this a deliberate naming decision?

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/nitro/issues/1
.
